# This one uses network=host, so ports will not have to be published, and EKG and Prometheus will be accessible from the host.
version: "3"
services:
  cardano-byron-producing: # block-producing node
    image: arrakis/cardano-node:pioneer2
    container_name: cardano-main-producing
    network_mode: host
    volumes:
      - $PWD/active_config/main/block-producing:/config
    environment:
      - PUID=1000
      - PGID=1001
      - NODE_PORT=3000
      - NODE_NAME=block-producing
      - NODE_TOPOLOGY=127.0.0.1:3001/1
      - NODE_RELAY=False
      - CARDANO_NETWORK=main
      - EKG_PORT=12788
      - PROMETHEUS_PORT=12798
      - RESOLVE_HOSTNAMES=True
      - REPLACE_EXISTING_CONFIG=True
    command: --start
    restart: unless-stopped
  cardano-byron-relay: # relay node
    image: arrakis/cardano-node:pioneer2
    container_name: cardano-main-relay
    network_mode: host
    volumes:
      - $PWD/active_config/main/relay1:/config
    environment:
      - PUID=1000
      - PGID=1001
      - NODE_PORT=3001
      - NODE_NAME=relay1
      - NODE_TOPOLOGY=127.0.0.1:3000/1
      - NODE_RELAY=True
      - CARDANO_NETWORK=main
      - EKG_PORT=12789
      - PROMETHEUS_PORT=12799
      - RESOLVE_HOSTNAMES=True
      - REPLACE_EXISTING_CONFIG=True
    command: --start
    restart: unless-stopped
