version: "3"
services:
  local-pioneer-producing: # block-producing node
    image: arrakis/cardano-node:1.13.0
    container_name: local-pioneer-producing
    network_mode: host
    volumes:
      - $PWD/config/local/:/config
    environment:
      - PUID=1000
      - PGID=1001
      - NODE_PORT=3000
      - NODE_NAME=local-block-producing
      - NODE_TOPOLOGY=127.0.0.1:3001/1
      - NODE_RELAY=False
      - CARDANO_NETWORK=pioneer
      - EKG_PORT=12888
      - PROMETHEUS_PORT=12898
      - HOST_ADDR=127.0.0.1
      - POOL_PLEDGE=100000000000
      - POOL_COST=10000000000
      - POOL_MARGIN=0.05
      - CREATE_STAKEPOOL=True
    command: --start
    restart: unless-stopped
  local-pioneer-relay: # relay node
    image: arrakis/cardano-node:1.13.0
    container_name: local-pioneer-relay
    network_mode: host
    volumes:
      - $PWD/config/local/:/config
    environment:
      - PUID=1000
      - PGID=1001
      - NODE_PORT=3001
      - NODE_NAME=local-relay1
      - NODE_TOPOLOGY=127.0.0.1:3000/1
      - NODE_RELAY=True
      - CARDANO_NETWORK=pioneer
      - EKG_PORT=12889
      - PROMETHEUS_PORT=12899
      - HOST_ADDR=127.0.0.1
    command: --start
    restart: unless-stopped